// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event.proto
// Protobuf Java Version: 4.35.1

package com.eventflow.proto;

@com.google.protobuf.Generated
public interface AnalyticsEventProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.eventflow.proto.AnalyticsEventProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string project_id = 2;</code>
   * @return The projectId.
   */
  java.lang.String getProjectId();
  /**
   * <code>string project_id = 2;</code>
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString
      getProjectIdBytes();

  /**
   * <code>string user_id = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string event_name = 4;</code>
   * @return The eventName.
   */
  java.lang.String getEventName();
  /**
   * <code>string event_name = 4;</code>
   * @return The bytes for eventName.
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <code>string properties_json = 5;</code>
   * @return The propertiesJson.
   */
  java.lang.String getPropertiesJson();
  /**
   * <code>string properties_json = 5;</code>
   * @return The bytes for propertiesJson.
   */
  com.google.protobuf.ByteString
      getPropertiesJsonBytes();

  /**
   * <code>int64 timestamp_millis = 6;</code>
   * @return The timestampMillis.
   */
  long getTimestampMillis();
}
