// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event.proto
// Protobuf Java Version: 4.35.1

package com.eventflow.proto;

@com.google.protobuf.Generated
public final class Event extends com.google.protobuf.GeneratedFile {
  private Event() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Event");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eventflow_proto_AnalyticsEventProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_eventflow_proto_AnalyticsEventProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\023com.eventflow.proto\"\223\001\n\023A" +
      "nalyticsEventProto\022\020\n\010event_id\030\001 \001(\t\022\022\n\n" +
      "project_id\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\t\022\022\n\neve" +
      "nt_name\030\004 \001(\t\022\027\n\017properties_json\030\005 \001(\t\022\030" +
      "\n\020timestamp_millis\030\006 \001(\003B:\n\023com.eventflo" +
      "w.protoP\001Z!server/ingestion-service-go/p" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_eventflow_proto_AnalyticsEventProto_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_eventflow_proto_AnalyticsEventProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_eventflow_proto_AnalyticsEventProto_descriptor,
        new java.lang.String[] { "EventId", "ProjectId", "UserId", "EventName", "PropertiesJson", "TimestampMillis", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
